### ISSUE TITLE
are pull request trying to also replace design documentation?

### ISSUE THREAD

**Issue by OluOyedipe** [githubteacher/github-for-developers-sept-2015#375]

**Comment by jaw6** [comment]
@OluOyedipe it's not really our intent to replace design documentation, but it does sometimes work out that way, in practice. The pull request persists as a document in the repository, recording _why_ a specific decision played out the way it did. Again, it's not :100:% intentional, but it does often work out, in practice, that a separate design document isn't totally necessary.
