### ISSUE TITLE
What's the grain of a github repositories?

### ISSUE THREAD

**Issue by rajkumar79** [githubteacher/github-for-developers-sept-2015#409]
What's the grain of github repositories? How nested they can be?

Are there any best practices of naming repositories?

Is it a good practice to have the following in a repository name.
1) Public vs Private Artifacts
2)Version Numbers.

**Comment by skchandon** [comment]
:+1:

**Comment by patrickmckenna** [comment]
@rajkumar79 @skchandon Good question.

You can have Git repositories as sub-directories of another Git project with something called `submodule`s. That said, we generally recommend avoiding that unless technically necessary. For instance, many people want to use `submodule`s to deal with project dependencies, but where possible we encourage you to use the appropriate package manager. `submodule`s typically become very tricky to work with.

A single project usually belongs in one repo, so the choice of name is often fairly straightforward. Since a Git repository contains the entire history of a project, you don't want to create separate repos to represent different releases. You can use Git `tag`s, or GitHub releases, to keep track of versions.

> Public vs Private Artifacts

Whether to store these in a repo depends on what you mean by private and artifact. If you're talking about things that ought to always be private, e.g. user credentials, _never_ store those in a Git repo. If you're talking about source code that can't be revealed publicly, you can create a private repository and control who has access to it.
