### ISSUE TITLE
Updating Git

### ISSUE THREAD

**Issue by maryfries** [githubteacher/github-for-developers-sept-2015#447]
How do you do it? My Desktop App is up to date, but my command line Git is seriously out of date.

**Comment by mnshantz** [comment]
:+1:

**Comment by saranicole** [comment]
:+1:

**Comment by jaw6** [comment]
@maryfries it depends a bit on your operating system. On Windows, try downloading from https://git-scm.com/download/win. On OS X, there are [instructions here](http://coolestguidesontheplanet.com/install-update-latest-version-git-mac-osx-10-9-mavericks/) for upgrading git. For Linux, it will depend on your specific package, for Ubuntu, `apt-get install git` ought to work.

**Comment by mnshantz** [comment]
I'm on a Windows machine and had previously installed git from the link above. But when I checked the git version I had 1.9.5 instead of 2.5.3. I tried reinstalling from the link provided and had the same result. I am using git shell (which for me was running in Windows PowerShell). I decided to check my git version using the Windows Command Prompt and found it is reporting version 2.5.3. What could cause the discrepency? How can I fix this?

**Comment by jaw6** [comment]
@mnshantz our application, GitHub for Windows, currently installs Git version 1.9.5 as "Git Shell", along with some sane default configuration enhancements (in other words: configures some things they way we [GitHub] find most Windows developers expect them to be). If you've installed Git from `git-scm.com`, the defaults install this as `Git Bash` (most likely under `Git` in your Start Menu, by default the installer doesn't add a `Git Bash` icon to the Windows desktop), but the `Git Shell` icon will still open a terminal with Git 1.9.5. 

Our Windows developers are telling me that GitHub for Windows with Git v2.5 will be shipping :soon:. If there aren't specific Git 2.x features you need _right now_, the best path might be to wait. Otherwise, you should be able to use `Git Bash` (or re-install from `git-scm.com`, but choose options for PowerShell -- the `Git Shell` icon installed by GitHub for Windows will still be pointing at 1.9.5, but you should be able to open a new Powershell from the Start Menu with 2.6).
