### ISSUE TITLE
git config --global push.default matching or simple

### ISSUE THREAD

**Issue by ap120266** [githubteacher/github-for-developers-sept-2015#528]
what is your default push setting?

**Comment by jaw6** [comment]
Typically, most folks want `current` or `simple` -- push the current branch to a branch with the same name at the remote. `matching` _used_ to be the default -- it pushes **all** branches with matching names. This can be dangerous (or at least, unintentional), especially for new-to-Git folks.

Imagine a scenario: You made some commits, but you were checked-out to `master` when you meant to be on a branch -- _ooops_. So, you check out a new branch, intending to go back to `reset` the `master` branch later, and then `$ git push` sends _all_ local matching branches -- not the new branch you just made (there's no matching remote yet) but it _does_ send `master` (because it matches `origin/master`). _Whoooops_.

**Comment by ap120266** [comment]
"simple" is good,

thanks,
andrew
