### ISSUE TITLE
branch vs fork

### ISSUE THREAD

**Issue by WoodyTheWoodman** [githubteacher/github-for-developers-sept-2015#529]
What is the difference between a branch and a fork? And when would you use one over the other?

**Comment by nathanv** [comment]
Good question. :+1:

**Comment by lkmorlan** [comment]
They are the same thing, though a fork implies that they will never be merged.

**Comment by patrickmckenna** [comment]
@WoodyTheWoodman Good question. First off, they are separate things. A branch exists within a repository. Any given repo can have an arbitrary number of branches, each representing a different revision of the project. We use branches to separate logically distinct work, both to make development easier and to sandbox work in progress.

A fork is a copy of an entire repository, including all its branches. In that sense, it's analogous to the copy of a repo you get with `git clone` &#8212; except that a fork lives on GitHub, not your local machine. Forks are used for access control, particularly in open source projects. Rather than giving the public at large write access to a repo, OSS maintainers typically request that contributors fork the main repository, make some changes on a branch _in their own fork_, then open a PR asking to merge that branch in the fork back into a branch the main repo.
