### ISSUE TITLE
How to find reference for deleted branch?

### ISSUE THREAD

**Issue by vb186017** [githubteacher/github-for-developers-sept-2015#668]
Once a branch is deleted, how do I find reference to that branch again? I can't find it under branch tab.
Just in case I want to restore the branch later.

**Comment by jaw6** [comment]
@vb186017 Git doesn't have a branch "Trash can" or "Recycle bin" mechanism to track branches that used to exist but have since been deleted. A branch is a pointer to a commit that follows as new commits are added "forward" of that commit in the repository. If you delete a branch and remember (or see in `git log`) the commit SHA id for where the branch used to be, you can restore it with:

```
git branch <name> <SHA>
```
