### ISSUE TITLE
Can you perform Git functions using the Git GUI?

### ISSUE THREAD

**Issue by TonyL-teradata** [githubteacher/github-for-developers-sept-2015#688]
I know you have not discussed about the Git GUI.

Can one use the Git GUI to perform Git functions (create branch, merge conflicts, etc), instead of using the command line?

**Comment by TonyL-teradata** [comment]
:+1:

**Comment by jaw6** [comment]
The Git GUI can do many things. We focus the class on the command line tools, since they work on every system; the Git GUI isn't always available. The terms, concepts, and workflows we cover in class will work with any GUI application; if we taught class with a specific GUI (even Git GUI) those concepts/workflows wouldn't _always_ translate 100% to any other GUI/application.
