### ISSUE TITLE
How to add a new folder in a branch and push to "origin"?

### ISSUE THREAD

**Issue by kaiyuan01** [githubteacher/github-for-developers-sept-2015#689]

**Comment by kaiyuan01** [comment]
:+1:

**Comment by saranicole** [comment]
You can use the `git add` command for a directory as you can for a file:
`git add mydirectory`

http://git-scm.com/docs/git-add

Then you will need to commit as usual:
`git commit`

Finally push:
`git push -u origin mybranch`

**Comment by jaw6** [comment]
Git, due to its design, doesn't track empty folders -- git _only_ tracks files. Files can be inside folders, but an empty folder, by itself, is "invisible" to Git.

In software development, it's common for projects to need an empty folder to be part of the project (a `log` directory, say, where the program can write log files, might need to exist on disk, even if we don't actually ever want to track log files in version control).

The convention for managing this in Git is to create a hidden file inside the folder you want to track. Files beginning with a "." (a period or dot) are treated as hidden files, so the convention is:

```
mkdir folder-to-track
touch folder-to-track/.gitkeep
git add folder-to-track
```

**Comment by saranicole** [comment]
Thanks @jaw6 for the clarification
