### ISSUE TITLE
Why the forking workflow has not been presented?

### ISSUE THREAD

**Issue by PinoEire** [githubteacher/github-for-developers-sept-2015#697]
IMO is the best one for cleaner production line, why it's been left out from the class?

**Comment by jaw6** [comment]
We focus on the most common workflows in class -- our students typically work in environments where collaborators interact within a common repository. Additionally, especially important for our classes, forking is an inherently more complicated workflow -- requiring managing multiple remotes, as well as understanding the differences between forks & branches. It's harder for folks totally new to version control, let alone git, to understand the forking model when starting from "square one" -- but once the "common repository" model makes sense, it's comparatively easy to adapt to a forking workflow.

Forking is most commonly seen in open source environments, where a "core" group has write access to the project repository, but a broad group of contributors use personal forks to submit Pull Requests. With minor modifications, the "common repository" workflows can be adapted to a forking workflow (eg, sending a pull request to the upstream repository rather than to the master branch of the common repository).
