### ISSUE TITLE
Protected repo's (i.e. master) is great.  What then is the process to allow merges?

### ISSUE THREAD

**Issue by rtauber92054** [githubteacher/github-for-developers-sept-2015#708]

**Comment by sbrinkmeyer** [comment]
we will be using this process where the ?lead? will be responsible for merging pull requests generated by other developers.  the other developers will not have the ability to do what we are doing (merging our own pull requests).  we could also set it up so that the individual branches are building & testing via a ci system and auto generate the pull request which in turn notifies the person responsible that "hey, i'm done, all my tests are good, i'm in synch with master, and my feature is ready ..."

**Comment by jaw6** [comment]
@rtauber92054 the first step of protected branches prevents the branch from being deleted or "force pushed" (which deletes history from the branch). There's a second (optional) step with protected branches that establishes one (or more) _required_ status (eg, from CI) before a pull request is allowed to be merged.
