### ISSUE TITLE
cherry-pick - what if branch is deleted after merging?

### ISSUE THREAD

**Issue by kcentofante** [githubteacher/github-for-developers-sept-2015#717]
In the example, hotfix was merged.  Best practice is to delete the branch.

Can I still use the "hotfix" branch name in the cherry-pick command if the branch was deleted after merge?

**Comment by jaw6** [comment]
`cherry-pick` targets a single commit via it's SHA. If you specific a branch (or tag) instead of a SHA id, git interprets that as if you had typed the SHA for the last commit in that branch.

In this case, if the branch has been deleted, you no longer have that handy pointer, you may need to find the specific SHA you're interested in picking.
